### ISSUE TITLE
How to overwrite nixpkgs

### ISSUE THREAD

**Issue by SuperSandro2000** [cachix/git-hooks.nix#141]
How can I overwrite in a downstream flake.nix nixpkgs which is normally done like ``inputs.nixpkgs.follows = "nixpkgs";``?

**Comment by SuperSandro2000** [comment]
Apparently you can just do the following

```nix
    pre-commit-hooks = {
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

but I don't understand why. It isn't listed here https://github.com/cachix/pre-commit-hooks.nix/blob/master/flake.nix#L4.

**Comment by akirak** [comment]
Nix looks up the flake registry (the global registry is [here](https://github.com/NixOS/flake-registry/)).
