### ISSUE TITLE
create a custom pre-commit install command which ensures the store paths used land in a derivation and are protected from gc

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [cachix/git-hooks.nix#161]

**Comment by roberth** [comment]
The `.pre-commit-config.yaml` symlink produced by the shellHook script is already a GC root. Does it not work for you?

**Comment by RonnyPfannschmidt** [comment]
@roberth then i missed a detail  - as per #160 i'd like to use a out of the checkout conifg file

if the in checkout file is also being used as gc root, then its a slightly different handling

**Comment by RonnyPfannschmidt** [comment]
@roberth i just hada nix gc destroy my pre-commit hook as installed, is there a way to fix that ?

**Comment by RonnyPfannschmidt** [comment]
@roberth what i observe is that practically every nix gc call wll destroy the pre commit hooks, including the config files

what can be done to sort that out?

**Comment by roberth** [comment]
Mine don't get GC-ed because lorri creates gc roots for the shells that reference them. Lorri shouldn't be a requirement though.

**Comment by sandydoo** [comment]
@roberth, in the shell hook, can't we replace the `ln -sf ...` that links our pre-commit config to the local `.pre-commit-config.yaml` with `nix-store --add-root "''${GIT_WC}/.pre-commit-config.yaml.gcroot" -r ${configFile}`? 
That gets us the symlink and the GC root in one go.

**Comment by roberth** [comment]
LGTM @sandydoo
