### ISSUE TITLE
Generate option docs

### ISSUE THREAD

**Issue by roberth** [cachix/git-hooks.nix#20]

**Comment by domenkozar** [comment]
The problem here is that we're setting `hooks` inside the config, so options docs don't really include the listing of the hooks.

**Comment by roberth** [comment]
Check this out, from #130: https://63668c68aaf1f30b3fa11fde--sprightly-cassata-33312f.netlify.app/options.html#opt-perSystem.pre-commit.settings.hooks

**Comment by jfly** [comment]
Are the rendered docs hosted anywhere? @roberth's link above still works, but it doesn't smell like something that's being kept up to date.

**Comment by domenkozar** [comment]
here: https://devenv.sh/reference/options/#pre-commit

**Comment by jfly** [comment]
Aha! Now I see that it's linked to from the README.

Should we close this issue?

**Comment by roberth** [comment]
> doesn't smell like something that's being kept up to date.

Was it because the project wasn't renamed yet? I just so happened work on that earlier today.

flake.parts is automatically updated twice a day, so it is up to date.

**Comment by roberth** [comment]
Oh wait, it's because of the link _in that comment_.
Now it's https://flake.parts/options/git-hooks-nix
