### ISSUE TITLE
document that this tool intentionaly violates key design decissions of pre-commit

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [cachix/git-hooks.nix#244]
pre-commit has a few key design decisions to keep users safe

1. hooks are isolated from the current repo
2. direct individual pinning control
3. the pre commit config file is a easy to read and review friendly part of the repository

this tool however shoehorns all of the control and pinning into a new file, makes the pre-commit configuration non-trackable file that cannot even use the normal standard pre-commit hooks anymore

if pre-commit was supposed to be proppery  integrated, then it ought to be something that lists flakes/apps for the hooks, but in the pre-commit config file that combines hook locks and cofiguration

**Comment by sandydoo** [comment]
Closing as nonconstructive.

This tool is used by people who use Nix to configure their dev environments. It does its job. And it's quite easy to use.
The current design uses pre-commit as an implementation detail. Other designs are possible, but if we were to explore them, it would be for exactly none of the above reasons.
