### ISSUE TITLE
Manual fourmolu override causes multiple problems

### ISSUE THREAD

**Issue by maralorn** [cachix/git-hooks.nix#316]
I believe because of https://github.com/cachix/pre-commit-hooks.nix/commit/e04dd8f275dcdd8ae7a895cd884aa5cc186f82d5, my shell needs to compile 15 minutes on every nixpkgs bump. Also my installed fourmolu version in the shell does not format the same way that pre-commit-nix expects.

I am not sure what to do about this, as you probably don’t want to revert. But I wanted to note that this is causing me problems.

Possible solutions:
* Revert the change
* Ignore (I’ll probably override the package for me locally.)
* Change the fourmolu in nixpkgs to version 0.12. Holding it back on the stackage version is kinda pointless, because we need to build a newer version for hls anyway. (And honestly, the installed binary and hls should use the same fourmolu version, ideally.)

**Comment by sandydoo** [comment]
Fixed in https://github.com/cachix/git-hooks.nix/pull/321.
