### ISSUE TITLE
Can the number of inputs/dependencies be lowered for the Flake?

### ISSUE THREAD

**Issue by toastal** [cachix/git-hooks.nix#445]
I have included a different project into my flake that had this project as a input & now my flake lock has exploded with new things I need to audit. Are all of these inputs actually required?

**Comment by sandydoo** [comment]
Could you please elaborate on this? What is your definition of "exploded" and which inputs do you consider redundant?

We're aware that the project ships with two versions of nixpkgs. We'd like to remove them at some point. Other than that, there's only 5 inputs...

**Comment by sandydoo** [comment]
Sure, we can replace `flake-utils` with the common `forAllSystems` function. I can merge that in, PRs welcome.
