### ISSUE TITLE
Ability to select specific versions of tooling

### ISSUE THREAD

**Issue by fiadliel** [cachix/git-hooks.nix#55]
Whether through passing in your own nixpkgs, sources.json, or otherwise, it would be nice to be able to influence the versions of tooling chosen, without having to fork the project.

A concrete case:
haskell-language-server for VSCode uses a specific version of ormolu for formatting, and this is built-in to the server as a library, not binary (with current hls, 0.1.2.0). If we can't align ormolu with the version pre-commit-hooks uses, then the feature in HLS/VSCode cannot reasonably be used concurrently with hooks (which is a pity for usability etc.).

**Comment by domenkozar** [comment]
It's possible to do that via `pre-commit.tools` or `entry` but you have to read the source to get it right.

It would be far better if we exposed package per each tool that could be overriden.

**Comment by domenkozar** [comment]
Similar to #61

**Comment by domenkozar** [comment]
This is now fixed, you can set `package` for each hook!
